version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=[[REPO URI]]
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 395995239202.dkr.ecr.ap-southeast-2.amazonaws.com/awsbuilders-dotnet:latest .
      - docker tag 395995239202.dkr.ecr.ap-southeast-2.amazonaws.com/awsbuilders-dotnet:latest 395995239202.dkr.ecr.ap-southeast-2.amazonaws.com/awsbuilders-dotnet:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 395995239202.dkr.ecr.ap-southeast-2.amazonaws.com/awsbuilders-dotnet:latest
      - docker push 395995239202.dkr.ecr.ap-southeast-2.amazonaws.com/awsbuilders-dotnet:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"awsbuilders-task-container","imageUri":"%s"}]' 395995239202.dkr.ecr.ap-southeast-2.amazonaws.com/awsbuilders-dotnet:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json

